### ISSUE TITLE
can i use this as a replacement for freeradius for vpn?

### ISSUE THREAD

**Issue by jinxmcg** [epiphyte/radiucal#24]
Hi, 

Can I use this project as AAA for ikev2 VPN like strngswan? 
How would one configure hostapd-server just to do the auth,acc from a mysql/redis db without any wifi/wired configs of hostapd...

Thank you

**Comment by storrgie** [comment]
This would be a question for [hostapd upstream](https://w1.fi/hostapd/), the mailing list is [here](http://lists.infradead.org/mailman/listinfo/hostap). Please examine the readme for this project, it is a proxy that sits in front of hostapd so that we can add features that are not necessarily in dot1x specification.

**Comment by enckse** [comment]
you should ask upstream for specifics per @storrgie 

if you have a question about configuration files you will find the hostapd tests will have example configs that may show you how to define things as you need them they are [here](https://w1.fi/cgit/hostap/tree/tests/hwsim/auth_serv) if you want to look at some sample config files (e.g. `eap_user.conf`)

**Comment by storrgie** [comment]
There was some discussion of combining hostapd and strongswan a [while back](https://lists.strongswan.org/pipermail/users/2012-February/002612.html) however I don't know where it ended up.

I know it's not likely hitting your use case @jinxmcg but you should also keep apprised of [wireguard](https://www.wireguard.com/).
